---
- name: Configure Database Server
  hosts: mysql_server
  become: true
  vars_files:
    - vault/vars.yml
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install MySQL packages
      package:
        name: "{{ item }}"
        state: present
      loop:
        - mysql-server
        - mysql-client
        - python3-pymysql

    - name: Start MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Comment out bind address in mysqld.cnf
      replace:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: "^bind-address"
        replace: "# bind-address"

    - name: Restart MySQL service
      service:
        name: mysql
        state: restarted

    - name: Create MySQL user
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        priv: "*.*:ALL"
        host: "%"
        state: present
